### ISSUE TITLE
iOS 16.7 app crashes due to connectivity plus in graphql-flutter

### ISSUE THREAD

**Issue by everfinal88** [Abdelazeem777/requests_inspector#25]
This crash only happen on this specific iOS 16.7 version. The issus is most likely due to connectivity plus version 3.0.6, the suggest solution is to downgrade it version 3.0.0. 

I'm not 100% sure this will fix the issue, but please look into this whenever it's possible. Thanks

Here's the reference for the crash issue :
[https://github.com/zino-hofmann/graphql-flutter/issues/1332#issuecomment-1564083936](url)

**Comment by Abdelazeem777** [comment]
Fixed on the latest version (3.3.1).

I am closing this issue for now, but please don't hesitate to open it again if you still facing any issues. 😊🙏
