### ISSUE TITLE
Open the inspector by tapping a specific button.

### ISSUE THREAD

**Issue by kiriyama-lvgs** [Abdelazeem777/requests_inspector#33]
Thanks for developing a great library.

Our app launches debug mode by shaking the device.
We would like to place a button to open the inspector in debug mode, so it would be nice to be able to tap a specific button to open the inspector.

**Comment by Abdelazeem777** [comment]
@kiriyama-lvgs 

What about using the other option of opening the inspector?

You can open the inspector by long-press on any free space on the screen.

Just enable the option by:
```dart
RequestsInspector(
    showInspectorOn: ShowInspectorOn.LongPress,
    ...
```

Please check this way and let me know if it working fine with you or not!

**Comment by Abdelazeem777** [comment]
Closed for now, but feel free to reopen it again if you are still facing any issues with provided solution 😊

**Comment by SyifaAinnur** [comment]
I think the inspector needs to additionally be able to be opened with a button, because if it is opened by long pressing on any empty space on the screen, it will be less convenient when there is a copy paste / block of text

**Comment by Abdelazeem777** [comment]
@SyifaAinnur 
I don't think so because if there is anything on the screen that can be pressed or long-pressed then it won't be considered a free space 🤷‍♂️

but, if you really need to have a custom button just to open the inspector then you can just call `showInspector` method from `InspectorController`
like this:
```dart
InkWell(
    child: Text('open inspector'),
    onTap: InspectorController().showInspector,
)
```
And that's it
