### ISSUE TITLE
Flutter GraphQL support?

### ISSUE THREAD

**Issue by santomalau03** [Abdelazeem777/requests_inspector#7]
Hello dev, is this package already support for flutter_graphql ?

Thank you

**Comment by Abdelazeem777** [comment]
Hi, @santomalau03 

Currently, requests_inspector doesn't support GraphQL.
But it's in my future plans.
Also, any PR for supporting GraphQL is most welcomed 

Thank you

**Comment by Abdelazeem777** [comment]
@santomalau03 
HasuraGraphQL supported 👌
flutter_graphql support is under development

**Comment by Abdelazeem777** [comment]
Now`flutter_graphql` is fully supported 🎉🎉
 
 using  `GraphQLInspectorLink `
 
 Ex.
 ```dart
 final client = GraphQLClient(
    cache: GraphQLCache(),
    link: Link.split(
      (request) => request.isSubscription,
      GraphQLInspectorLink(WebSocketLink('ws://graphqlzero.almansi.me/api')),
      GraphQLInspectorLink(HttpLink('https://graphqlzero.almansi.me/api')),
    ),
  );
 ```
